export const ADD_USER = "ADD_USER"
export const REMOVE_USER = "REMOVE_USER"
export const ADD_CART = "ADD_CART"
export const REMOVE_PRODUCT = "REMOVE_PRODUCT"
export const ADD_PRODUCTS = "ADD_PRODUCTS"